<a href="https://colab.research.google.com/github/canerskrc/Borusan_Kod_Adi_Dijital/blob/main/Borusan_day_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

#VERÄ° OKUMA

In [2]:
df = pd.read_csv("car data.csv")

In [3]:
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

#VERÄ° Ä°NCELEME

In [5]:
df.shape

(301, 9)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [8]:
df.describe()

              Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [9]:
df["Fuel_Type"].unique()

array(['Petrol', 'Diesel', 'CNG'], dtype=object)

In [10]:
if "Fuel_Type" in df.columns:
  print("YakÄ±t tÃ¼rÃ¼ daÄÄ±lÄ±mÄ±:\n", df["Fuel_Type"].value_counts())

YakÄ±t tÃ¼rÃ¼ daÄÄ±lÄ±mÄ±:
 Fuel_Type
Petrol    239
Diesel     60
CNG         2
Name: count, dtype: int64

In [11]:
df.sample(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
19,sx4,2010,2.65,7.980,41442,Petrol,Dealer,Manual,0
150,TVS Apache RTR 180,2011,0.50,0.826,6000,Petrol,Individual,Manual,0
149,Bajaj Pulsar 220 F,2016,0.51,0.940,24000,Petrol,Individual,Manual,0
65,etios liva,2014,4.75,6.950,45000,Diesel,Dealer,Manual,0
103,Bajaj Dominar 400,2017,1.45,1.600,1200,Petrol,Individual,Manual,0

In [12]:
df.memory_usage(deep=True)

Index              132
Car_Name         17716
Year              2408
Selling_Price     2408
Present_Price     2408
Kms_Driven        2408
Fuel_Type        16549
Seller_Type      16979
Transmission     16675
Owner             2408
dtype: int64

In [13]:
print(df.describe(include="all"))

       Car_Name         Year  Selling_Price  Present_Price     Kms_Driven  \
count       301   301.000000     301.000000     301.000000     301.000000
unique       98          NaN            NaN            NaN            NaN
top        city          NaN            NaN            NaN            NaN
freq         26          NaN            NaN            NaN            NaN
mean        NaN  2013.627907       4.661296       7.628472   36947.205980
std         NaN     2.891554       5.082812       8.644115   38886.883882
min         NaN  2003.000000       0.100000       0.320000     500.000000
25%         NaN  2012.000000       0.900000       1.200000   15000.000000
50%         NaN  2014.000000       3.600000       6.400000   32000.000000
75%         NaN  2016.000000       6.000000       9.900000   48767.000000
max         NaN  2018.000000      35.000000      92.600000  500000.000000

       Fuel_Type Seller_Type Transmission       Owner
count        301         301          301  301.000000
unique         3           2            2         NaN
top       Petrol      Dealer       Manual         NaN
freq         239         195          261         NaN
mean         NaN         NaN          NaN    0.043189
std          NaN         NaN          NaN    0.247915
min          NaN         NaN          NaN    0.000000
25%          NaN         NaN          NaN    0.000000
50%          NaN         NaN          NaN    0.000000
75%          NaN         NaN          NaN    0.000000
max          NaN         NaN          NaN    3.000000

In [14]:
print(df["Year"].unique())

[2014 2013 2017 2011 2018 2015 2016 2009 2010 2012 2003 2008 2006 2005
 2004 2007]

In [15]:
df["Year"].value_counts()

Year
2015    61
2016    50
2014    38
2017    35
2013    33
2012    23
2011    19
2010    15
2008     7
2009     6
2005     4
2006     4
2007     2
2003     2
2018     1
2004     1
Name: count, dtype: int64

In [16]:
df.drop_duplicates().shape[0]

299

#SEÃME & FÄ°LTRELEME

In [18]:
print(df["Year"].head())

0    2014
1    2013
2    2017
3    2011
4    2014
Name: Year, dtype: int64

In [19]:
df[["Fuel_Type","Car_Name"]].head()

  Fuel_Type Car_Name
0    Petrol     ritz
1    Diesel      sx4
2    Petrol     ciaz
3    Petrol  wagon r
4    Diesel    swift

In [20]:
df.loc[0:4, ["Car_Name","Fuel_Type","Year"]]

  Car_Name Fuel_Type  Year
0     ritz    Petrol  2014
1      sx4    Diesel  2013
2     ciaz    Petrol  2017
3  wagon r    Petrol  2011
4    swift    Diesel  2014

In [21]:
df.iloc[0:4, 0:3]

  Car_Name  Year  Selling_Price
0     ritz  2014           3.35
1      sx4  2013           4.75
2     ciaz  2017           7.25
3  wagon r  2011           2.85

In [ ]:
X = df.iloc[:, :-1] # son sÃ¼tun hariÃ§ tÃ¼m sÃ¼tunlar.
y =

train = df.iloc[:8000] # ilk 8000 satÄ±r. (0'dan 7999. veriye kadar alÄ±r 8000. veri dahil olmaz.)
test = df.iloc[8000:] # geri kalan tÃ¼m veriler.(8000. veriden sona kadar.)

In [25]:
luxury = df.query("Selling_Price > 5 and Fuel_Type == 'Petrol'")
print(luxury.head())

   Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
2      ciaz  2017           7.25           9.85        6900    Petrol
6      ciaz  2015           6.75           8.12       18796    Petrol
12     ciaz  2015           7.50           9.94       15000    Petrol
13   ertiga  2015           6.10           7.71       26000    Petrol
27    swift  2017           6.00           6.49       16200    Petrol

   Seller_Type Transmission  Owner
2       Dealer       Manual      0
6       Dealer       Manual      0
12      Dealer    Automatic      0
13      Dealer       Manual      0
27  Individual       Manual      0

In [27]:
bmw_audi = df[df["Car_Name"].isin(["BMW","Audi"])]
print(bmw_audi)

Empty DataFrame
Columns: [Car_Name, Year, Selling_Price, Present_Price, Kms_Driven, Fuel_Type, Seller_Type, Transmission, Owner]
Index: []

#VERÄ° TEMÄ°ZLEME

In [28]:
df.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [ ]:
#Eksik verileri ortalama ile doldurma

df["Selling_Price"] = df["Selling_Price"].fillna(df["Selling_Price"].mean())

#eksik satÄ±rlarÄ± silme

df = df.dropna(subset=["Year"])

#Tekrar eden deÄerleri kaldÄ±r

In [29]:
df = df.drop_duplicates()

In [30]:
df.sample(6)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
223,verna,2015,8.25,9.40,61381,Diesel,Dealer,Manual,0
184,Bajaj Pulsar 150,2008,0.25,0.75,26000,Petrol,Individual,Manual,1
164,Hero Splender iSmart,2016,0.45,0.54,14000,Petrol,Individual,Manual,0
29,ciaz,2015,7.45,10.38,45000,Diesel,Dealer,Manual,0
64,fortuner,2017,33.00,36.23,6000,Diesel,Dealer,Automatic,0
111,Royal Enfield Thunder 350,2016,1.15,1.50,8700,Petrol,Individual,Manual,0

In [31]:
df = df.rename(columns={"Selling_Price":"Price"})

In [32]:
df.head()

,Car_Name,Year,Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [33]:
df["Year"]= df["Year"].astype(int)

In [34]:
df["Year"].head()

0    2014
1    2013
2    2017
3    2011
4    2014
Name: Year, dtype: int64

#VERÄ° MANÄ°PÃLASYONU

In [36]:
dt = pd.read_csv("Car details v3.csv")

In [37]:
#yeni sÃ¼tun oluÅturma
dt.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0

In [39]:
dt["mileage"] = dt["mileage"].astype(int)

ValueError: invalid literal for int() with base 10: '23.4 kmpl'

In [38]:
dt["price_per_mile"] = dt["selling_price"] / (dt["mileage"])

TypeError: unsupported operand type(s) for /: 'int' and 'str'

In [40]:
dt["owner_main"] = dt["owner"].str.split().str[0]

In [41]:
dt["owner_main"].head()

0     First
1    Second
2     Third
3     First
4     First
Name: owner_main, dtype: object

In [42]:
dt["mileage_main"] = dt["mileage"].str.split().str[0]

In [43]:
dt["mileage_main"].head()

0     23.4
1    21.14
2     17.7
3     23.0
4     16.1
Name: mileage_main, dtype: object

In [44]:
dt["price_per_mile"] = dt["selling_price"] / (dt["mileage_main"])

TypeError: unsupported operand type(s) for /: 'int' and 'str'

In [46]:
dt["mileage_main"] = dt["mileage_main"].astype(float)

In [47]:
dt["price_per_mile"] = dt["selling_price"] / (dt["mileage_main"])

In [48]:
dt["price_per_mile"].head()

0    19230.769231
1    17502.365184
2     8926.553672
3     9782.608696
4     8074.534161
Name: price_per_mile, dtype: float64

In [49]:
dt["price_log"] = dt["selling_price"].apply(np.log1p)

In [50]:
dt["price_log"].head()

0    13.017005
1    12.821261
2    11.970357
3    12.323860
4    11.775297
Name: price_log, dtype: float64

In [51]:
dt.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,owner_main,mileage_main,price_per_mile,price_log
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,First,23.40,19230.769231,13.017005
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,Second,21.14,17502.365184,12.821261
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,Third,17.70,8926.553672,11.970357
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,First,23.00,9782.608696,12.323860
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,First,16.10,8074.534161,11.775297

In [53]:
dt['fuel_label'] = dt["fuel"].map({
    "Petrol":"Benzin",
    "Diesel":"Dizel",
    "CNG":"SÄ±kÄ±ÅtÄ±rÄ±lmÄ±ÅGaz",
    "LPG":"LPG"})
dt["fuel_label"].head()

0     Dizel
1     Dizel
2    Benzin
3     Dizel
4    Benzin
Name: fuel_label, dtype: object

In [54]:
dt = dt.assign(is_luxury = dt["selling_price"] > 300000)

In [55]:
dt.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,owner_main,mileage_main,price_per_mile,price_log,fuel_label,is_luxury
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,First,23.40,19230.769231,13.017005,Dizel,True
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,Second,21.14,17502.365184,12.821261,Dizel,True
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,Third,17.70,8926.553672,11.970357,Benzin,False
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,First,23.00,9782.608696,12.323860,Dizel,False
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,First,16.10,8074.534161,11.775297,Benzin,False

In [56]:
dtf= pd.DataFrame({
    "car":["bmw","audi"],
    "features":[["Sunroof","leather"],["bluetooth","gps"]]
    })
print(dtf.explode("features"))

    car   features
0   bmw    Sunroof
0   bmw    leather
1  audi  bluetooth
1  audi        gps

In [58]:
dt_melt = dt.melt(
    id_vars=["name","year"], # sabit kalacak sÃ¼tunlar
    value_vars=["selling_price","km_driven"], #long'a Ã§evrilecek sÃ¼tunlar
    var_name="metric", value_name="value"

)

print(dt_melt.head())

                           name  year         metric   value
0        Maruti Swift Dzire VDI  2014  selling_price  450000
1  Skoda Rapid 1.5 TDI Ambition  2014  selling_price  370000
2      Honda City 2017-2020 EXi  2006  selling_price  158000
3     Hyundai i20 Sportz Diesel  2010  selling_price  225000
4        Maruti Swift VXI BSIII  2007  selling_price  130000

In [59]:
dt_pivot = dt.pivot_table(
    values="selling_price",
    index="name",
    columns="fuel",
    aggfunc="mean"
)
print(dt_pivot)

fuel                               CNG     Diesel  LPG      Petrol
name
Ambassador CLASSIC 1500 DSL AC     NaN    75000.0  NaN         NaN
Ambassador Classic 2000 DSZ AC PS  NaN    99000.0  NaN         NaN
Ambassador Grand 1500 DSZ BSIII    NaN   122000.0  NaN         NaN
Ambassador Grand 2000 DSZ PW CL    NaN   200000.0  NaN         NaN
Ashok Leyland Stile LE             NaN   300000.0  NaN         NaN
...                                ...        ...  ...         ...
Volvo V40 D3 R-Design              NaN  2475000.0  NaN         NaN
Volvo XC40 D4 Inscription BSIV     NaN  3800000.0  NaN         NaN
Volvo XC40 D4 R-Design             NaN  3400000.0  NaN         NaN
Volvo XC60 Inscription D5 BSIV     NaN  5500000.0  NaN         NaN
Volvo XC90 T8 Excellence BSIV      NaN        NaN  NaN  10000000.0

[2058 rows x 4 columns]

#VERÄ° BÄ°RLEÅTÄ°RME

In [62]:
dt_all = pd.concat([dt.head(100),dt.tail(100)])
dt_all

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,owner_main,mileage_main,price_per_mile,price_log,fuel_label,is_luxury
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,First,23.40,19230.769231,13.017005,Dizel,True
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,Second,21.14,17502.365184,12.821261,Dizel,True
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,Third,17.70,8926.553672,11.970357,Benzin,False
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,First,23.00,9782.608696,12.323860,Dizel,False
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,First,16.10,8074.534161,11.775297,Benzin,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0,First,18.50,17297.297297,12.676079,Benzin,True
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,"24@ 1,900-2,750(kgm@ rpm)",5.0,Fourth,16.80,8035.714286,11.813037,Dizel,False
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5.0,First,19.30,19792.746114,12.853179,Dizel,True
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0,First,23.57,12303.775986,12.577640,Dizel,False
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0,First,23.57,12303.775986,12.577640,Dizel,False

In [63]:
dt_avg = dt.groupby("name")["selling_price"].mean().reset_index()
dt_merged = pd.merge(dt, dt_avg, on="name", suffixes=("","_avg"))

In [64]:
dt_merged

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,owner_main,mileage_main,price_per_mile,price_log,fuel_label,is_luxury,selling_price_avg
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,First,23.40,19230.769231,13.017005,Dizel,True,578658.860465
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,Second,21.14,17502.365184,12.821261,Dizel,True,540000.000000
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,Third,17.70,8926.553672,11.970357,Benzin,False,165142.857143
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,First,23.00,9782.608696,12.323860,Dizel,False,225000.000000
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,First,16.10,8074.534161,11.775297,Benzin,False,150000.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0,First,18.50,17297.297297,12.676079,Benzin,True,295937.437500
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,"24@ 1,900-2,750(kgm@ rpm)",5.0,Fourth,16.80,8035.714286,11.813037,Dizel,False,219111.111111
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5.0,First,19.30,19792.746114,12.853179,Dizel,True,308714.285714
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0,First,23.57,12303.775986,12.577640,Dizel,False,232285.642857
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0,First,23.57,12303.775986,12.577640,Dizel,False,232285.642857

#NUMPY MASKELEME/ INDEKSLEME

In [65]:
dtr = pd.read_csv("car details v4.csv")
dtr.head()

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0

In [66]:
arr = np.arange(1,13)#1 den 12 ye kadar array oluÅturur.
print("orijinal:", arr)

orijinal: [ 1  2  3  4  5  6  7  8  9 10 11 12]

In [67]:
mat = arr.reshape(3,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
mat.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [69]:
np.where(arr > 5, "BÃ¼yÃ¼k","KÃ¼Ã§Ã¼k")

array(['KÃ¼Ã§Ã¼k', 'KÃ¼Ã§Ã¼k', 'KÃ¼Ã§Ã¼k', 'KÃ¼Ã§Ã¼k', 'KÃ¼Ã§Ã¼k', 'BÃ¼yÃ¼k', 'BÃ¼yÃ¼k',
       'BÃ¼yÃ¼k', 'BÃ¼yÃ¼k', 'BÃ¼yÃ¼k', 'BÃ¼yÃ¼k', 'BÃ¼yÃ¼k'], dtype='<U5')

In [70]:
np.take(arr,[0,4,7])

array([1, 5, 8])

In [72]:
np.put(arr, [0,3],[99,77])
arr

array([99,  2,  3, 77,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
arr1  = np.array([10,20,30,40])
choice = np.choose([0,1,0,1], [arr1, arr1*10])
choice

array([ 10, 200,  30, 400])

#MATEMATÄ°KSEL METOTLAR

In [78]:
prices = dtr["Price"].to_numpy()

print(np.median(prices))
print(np.percentile(prices, 25))
print(np.percentile(prices, 75))

hist, bins = np.histogram(prices, bins=10)
print(hist)
print(bins)

825000.0
484999.0
1925000.0
[1801  198   38    9    2    7    2    1    0    1]
[   49000.  3544100.  7039200. 10534300. 14029400. 17524500. 21019600.
 24514700. 28009800. 31504900. 35000000.]

In [79]:
print("100.000 ile 250000 aralÄ±ÄÄ±ndaki araÃ§lar: ", np.clip(prices, 100000,250000))

100.000 ile 250000 aralÄ±ÄÄ±ndaki araÃ§lar:  [250000 250000 220000 ... 240000 250000 250000]

In [83]:
years = dtr["Year"].to_numpy()
np.corrcoef(prices,years)

array([[1.        , 0.31139954],
       [0.31139954, 1.        ]])